version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    volumes:
      - type: bind
        source: ../static-php-cli
        target: /workspace
    working_dir: /workspace
    tty: true